// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Save provides a mock function with given fields: file, dir, filename
func (_m *Storage) Save(file *multipart.FileHeader, dir string, filename string) (string, error) {
	ret := _m.Called(file, dir, filename)

	var r0 string
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string, string) string); ok {
		r0 = rf(file, dir, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, string, string) error); ok {
		r1 = rf(file, dir, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
