// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/ardafirdausr/posjoo-server/internal/entity"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, param
func (_m *UserUsecase) CreateUser(ctx context.Context, param entity.CreateUserParam) (*entity.User, error) {
	ret := _m.Called(ctx, param)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateUserParam) *entity.User); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateUserParam) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *UserUsecase) DeleteUser(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchantUsers provides a mock function with given fields: ctx, merchantID
func (_m *UserUsecase) GetMerchantUsers(ctx context.Context, merchantID int64) ([]*entity.User, error) {
	ret := _m.Called(ctx, merchantID)

	var r0 []*entity.User
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entity.User); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *UserUsecase) GetUser(ctx context.Context, userID int64) (*entity.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, userID, param
func (_m *UserUsecase) UpdateUser(ctx context.Context, userID int64, param entity.UpdateUserParam) (*entity.User, error) {
	ret := _m.Called(ctx, userID, param)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.UpdateUserParam) *entity.User); ok {
		r0 = rf(ctx, userID, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, entity.UpdateUserParam) error); ok {
		r1 = rf(ctx, userID, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPassword provides a mock function with given fields: ctx, userID, param
func (_m *UserUsecase) UpdateUserPassword(ctx context.Context, userID int64, param entity.UpdateUserPasswordParam) error {
	ret := _m.Called(ctx, userID, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.UpdateUserPasswordParam) error); ok {
		r0 = rf(ctx, userID, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserPhoto provides a mock function with given fields: ctx, userID, photo
func (_m *UserUsecase) UpdateUserPhoto(ctx context.Context, userID int64, photo *multipart.FileHeader) (*entity.User, error) {
	ret := _m.Called(ctx, userID, photo)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, int64, *multipart.FileHeader) *entity.User); ok {
		r0 = rf(ctx, userID, photo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, userID, photo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
