DROP DATABASE IF EXISTS posjoo
CREATE DATABASE posjoo
USE posjoo;

DROP TABLE IF EXISTS merchants;
CREATE TABLE merchants (
	id INT(20) UNSIGNED AUTO_INCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL ,
	address VARCHAR(255) NOT NULL ,
	phone VARCHAR(15) NULL DEFAULT NULL ,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT(20) UNSIGNED AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL ,
	email VARCHAR(50) NOT NULL ,
	photo_url VARCHAR(255) NULL DEFAULT NULL ,
	role ENUM('owner', 'manager', 'staff') NOT NULL ,
	password VARCHAR(255) NOT NULL ,
	merchant_id INT(10) UNSIGNED  NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (id),
	UNIQUE USERS_EMAIL (email),
	FOREIGN KEY (merchant_id) REFERENCES merchants(id)
) ENGINE = InnoDB;

DROP TABLE products;
CREATE TABLE products (
	id INT(20) UNSIGNED AUTO_INCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL ,
	sku VARCHAR(50) NOT NULL,
	photo_url VARCHAR(255) NULL DEFAULT NULL,
	merchant_id INT(10) UNSIGNED  NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (id),
  UNIQUE PRODUCTS_SKU (merchant_id, sku),
	FOREIGN KEY (merchant_id) REFERENCES merchants(id)
) ENGINE = InnoDB;

